/** Bảng Niêm Yết TTHC - UBND xã Vĩnh Bảo (Hải Phòng)
 * Nguồn: PDF Danh mục TTHC cấp xã TP Hải Phòng, Thông báo 46/TB-UBND,
 * Cổng DVC, vinhbao.haiphong.gov.vn
 * Ghi chú: Danh mục dưới đây gồm thủ tục trích từ phụ lục VH-XH (~133 TTHC)
 * + nhóm Hộ tịch/Chứng thực giải quyết nhanh + một số TTHC phổ biến khác.
 * Toàn bộ ~400 TTHC cấp xã (đất đai, xây dựng, nông nghiệp...) cần bổ sung
 * tiếp từ file DANH MUC THU TUC HANH CHINH CAP XA (MOI).pdf khi có.
 */
window.TTHC_DATA = {
  donVi: "UBND xã Vĩnh Bảo",
  diaChi: "Đường 20/8, xã Vĩnh Bảo, thành phố Hải Phòng",
  hotline: "0823.919.686",
  canBo: [
    { ten: "Nguyễn Hồng Diễn", chucVu: "Giám đốc Trung tâm PVHCC", sdt: "0823.919.686" },
    { ten: "Phạm Trung Anh", chucVu: "Phó giám đốc Trung tâm", sdt: "0967.311.138" },
    { ten: "Lâm Thị Oanh", chucVu: "CV Địa chính, môi trường, ĐKKD", sdt: "0398.188.930" },
    { ten: "Lê Hồng Quân", chucVu: "CV Tư pháp - Hộ tịch", sdt: "0948.232.192" },
    { ten: "Phạm Thị Soạn", chucVu: "CV Văn hóa - xã hội", sdt: "0383.299.929" },
    { ten: "Nguyễn Thị Mai Phượng", chucVu: "CV Văn thư và trả kết quả", sdt: "0786.676.135" }
  ],
  ghiChuNhanh: "Một số TTHC giải quyết nhanh và trả kết quả trong ngày vào thứ Tư hằng tuần (Thông báo 46/TB-UBND xã Vĩnh Bảo).",
  linhVuc: [
    { id: "lv01", ten: "HỘ TỊCH" },
    { id: "lv02", ten: "CHỨNG THỰC" },
    { id: "lv03", ten: "ĐẤT ĐAI" },
    { id: "lv04", ten: "HOẠT ĐỘNG XÂY DỰNG" },
    { id: "lv05", ten: "BẢO TRỢ XÃ HỘI" },
    { id: "lv06", ten: "DÂN SỐ, BÀ MẸ - TRẺ EM" },
    { id: "lv07", ten: "TRẺ EM" },
    { id: "lv08", ten: "GIA ĐÌNH" },
    { id: "lv09", ten: "PHÒNG, CHỐNG TỆ NẠN XÃ HỘI" },
    { id: "lv10", ten: "NGƯỜI CÓ CÔNG" },
    { id: "lv11", ten: "TÍN NGƯỠNG, TÔN GIÁO" },
    { id: "lv12", ten: "CÔNG TÁC DÂN TỘC" },
    { id: "lv13", ten: "GIÁO DỤC MẦM NON" },
    { id: "lv14", ten: "GIÁO DỤC TIỂU HỌC" },
    { id: "lv15", ten: "GIÁO DỤC TRUNG HỌC" },
    { id: "lv16", ten: "GIÁO DỤC THƯỜNG XUYÊN" },
    { id: "lv17", ten: "GIÁO DỤC NGHỀ NGHIỆP" },
    { id: "lv18", ten: "CÁC CƠ SỞ GIÁO DỤC KHÁC" },
    { id: "lv19", ten: "GIÁO DỤC VÀ ĐÀO TẠO" },
    { id: "lv20", ten: "VĂN BẰNG, CHỨNG CHỈ" },
    { id: "lv21", ten: "VĂN HOÁ" },
    { id: "lv22", ten: "THỂ DỤC THỂ THAO" },
    { id: "lv23", ten: "PHÁT THANH, TRUYỀN HÌNH VÀ THÔNG TIN ĐIỆN TỬ" },
    { id: "lv24", ten: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ" },
    { id: "lv25", ten: "VIỆC LÀM" },
    { id: "lv26", ten: "QUẢN LÝ LAO ĐỘNG NGOÀI NƯỚC" },
    { id: "lv27", ten: "HÒA GIẢI CƠ SỞ" },
    { id: "lv28", ten: "NUÔI CON NUÔI" },
    { id: "lv29", ten: "HỘ KINH DOANH" },
    { id: "lv30", ten: "MÔI TRƯỜNG" },
    { id: "lv31", ten: "NÔNG NGHIỆP" },
    { id: "lv32", ten: "ĐƯỜNG BỘ" },
    { id: "lv33", ten: "HÀNG HẢI VÀ ĐƯỜNG THỦY" },
    { id: "lv34", ten: "LÂM NGHIỆP" },
    { id: "lv35", ten: "CHĂN NUÔI" },
    { id: "lv36", ten: "THỦY SẢN" },
    { id: "lv37", ten: "GIẢM NGHÈO" },
    { id: "lv38", ten: "QUẢN LÝ ĐÊ ĐIỀU VÀ PCTT" },
    { id: "lv39", ten: "TÀI CHÍNH ĐẤT ĐAI" },
    { id: "lv40", ten: "NHÀ Ở VÀ CÔNG SỞ" },
    { id: "lv41", ten: "LƯU THÔNG HÀNG HÓA TRONG NƯỚC" },
    { id: "lv42", ten: "TRỒNG TRỌT" },
    { id: "lv43", ten: "BIỂN VÀ HẢI ĐẢO" },
    { id: "lv44", ten: "KINH DOANH KHÍ" },
    { id: "lv45", ten: "THỦY LỢI" },
    { id: "lv46", ten: "THỦY SẢN" },
    { id: "lv47", ten: "CHĂN NUÔI" },
    { id: "lv48", ten: "THÚ Y" },
    { id: "lv49", ten: "LÂM NGHIỆP" },
    { id: "lv50", ten: "GIẢM NGHÈO" },
    { id: "lv51", ten: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC" },
    { id: "lv52", ten: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC, HỢP TÁC XÃ" },
    { id: "lv53", ten: "HỖ TRỢ TỔ HỢP TÁC, HỢP TÁC XÃ" },
    { id: "lv54", ten: "KHOÁNG SẢN" },
    { id: "lv55", ten: "KIỂM LÂM" },
    { id: "lv56", ten: "KINH TẾ HỢP TÁC VÀ PHÁT TRIỂN NÔNG THÔN" },
    { id: "lv57", ten: "BẢO TỒN THIÊN NHIÊN VÀ ĐA DẠNG SINH HỌC" },
    { id: "lv58", ten: "TÀI NGUYÊN NƯỚC" },
    { id: "lv59", ten: "QUY HOẠCH XÂY DỰNG, KIẾN TRÚC" },
    { id: "lv60", ten: "CÔNG NGHIỆP ĐỊA PHƯƠNG" },
    { id: "lv61", ten: "BỒI THƯỜNG NHÀ NƯỚC" },
    { id: "lv62", ten: "QUẢN LÝ CÔNG SẢN" },
    { id: "lv63", ten: "TÀI SẢN KẾT CẤU HẠ TẦNG CHỢ" },
    { id: "lv64", ten: "BẢO HIỂM" },
    { id: "lv65", ten: "XỬ LÝ ĐƠN THƯ" },
    { id: "lv66", ten: "GIẢI QUYẾT KHIẾU NẠI" },
    { id: "lv67", ten: "GIẢI QUYẾT TỐ CÁO" },
    { id: "lv68", ten: "PHÒNG, CHỐNG THAM NHŨNG" },
    { id: "lv69", ten: "PHỔ BIẾN GIÁO DỤC PHÁP LUẬT" },
    { id: "lv70", ten: "ĐĂNG KÝ CƯ TRÚ" }
  ],
  thuTuc: [
    { stt: 1, ma: "1.001193", ten: "Đăng ký khai sinh", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: true },
    { stt: 2, ma: "1.000124", ten: "Đăng ký khai tử", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: true },
    { stt: 3, ma: "1.000125", ten: "Đăng ký kết hôn", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: true },
    { stt: 4, ma: "1.000126", ten: "Cấp giấy xác nhận tình trạng hôn nhân", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: true },
    { stt: 5, ma: "1.000127", ten: "Cấp bản sao trích lục hộ tịch, bản sao giấy khai sinh", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: true },
    { stt: 6, ma: "1.000128", ten: "Xác nhận thông tin hộ tịch", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: true },
    { stt: 7, ma: "1.000129", ten: "Ghi vào Sổ hộ tịch việc hộ tịch khác của công dân VN đã giải quyết tại nước ngoài", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: true },
    { stt: 8, ma: "1.000130", ten: "Ghi vào Sổ hộ tịch việc ly hôn, hủy việc kết hôn của công dân VN đã giải quyết tại nước ngoài", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: true },
    { stt: 9, ma: "1.000201", ten: "Chứng thực bản sao từ bản chính", linhVuc: "CHỨNG THỰC", cap: "Xã", nhanh: true },
    { stt: 10, ma: "1.000202", ten: "Chứng thực hợp đồng, giao dịch", linhVuc: "CHỨNG THỰC", cap: "Xã", nhanh: true },
    { stt: 11, ma: "1.000203", ten: "Chứng thực chữ ký", linhVuc: "CHỨNG THỰC", cap: "Xã", nhanh: false },
    { stt: 12, ma: "1.013821", ten: "Thực hiện, điều chỉnh, tạm dừng, thôi hưởng trợ cấp sinh hoạt hàng tháng đối với nghệ nhân ND, NN ưu tú có thu nhập thấp", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 13, ma: "1.013822", ten: "Hỗ trợ chi phí mai táng đối với nghệ nhân ND, NN ưu tú có thu nhập thấp", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 14, ma: "1.001776", ten: "Thực hiện, điều chỉnh, thôi hưởng trợ cấp xã hội hàng tháng, hỗ trợ kinh phí chăm sóc, nuôi dưỡng hàng tháng", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 15, ma: "1.001731", ten: "Hỗ trợ chi phí mai táng cho đối tượng bảo trợ xã hội", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 16, ma: "1.001699", ten: "Xác định, xác định lại mức độ khuyết tật và cấp Giấy xác nhận khuyết tật", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 17, ma: "1.001653", ten: "Đổi, cấp lại Giấy xác nhận khuyết tật", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 18, ma: "2.000477", ten: "Dừng trợ giúp xã hội tại cơ sở trợ giúp xã hội", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 19, ma: "2.000355", ten: "Đăng ký hoạt động đối với cơ sở trợ giúp xã hội dưới 10 đối tượng có hoàn cảnh khó khăn", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 20, ma: "2.000286", ten: "Tiếp nhận đối tượng bảo trợ xã hội có hoàn cảnh đặc biệt khó khăn vào cơ sở trợ giúp xã hội", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 21, ma: "2.000282", ten: "Tiếp nhận đối tượng cần bảo vệ khẩn cấp vào cơ sở trợ giúp xã hội", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 22, ma: "2.001088", ten: "Xét hưởng chính sách hỗ trợ cho đối tượng sinh con đúng chính sách dân số", linhVuc: "DÂN SỐ, BÀ MẸ - TRẺ EM", cap: "Xã", nhanh: false },
    { stt: 23, ma: "1.010939", ten: "Công bố lại tổ chức, cá nhân cung cấp dịch vụ cai nghiện ma túy tự nguyện tại gia đình, cộng đồng", linhVuc: "PHÒNG, CHỐNG TỆ NẠN XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 24, ma: "1.010941", ten: "Đăng ký cai nghiện ma túy tự nguyện", linhVuc: "PHÒNG, CHỐNG TỆ NẠN XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 25, ma: "1.010940", ten: "Công bố cơ sở cai nghiện ma túy tự nguyện, cơ sở cai nghiện ma túy công lập đủ điều kiện", linhVuc: "PHÒNG, CHỐNG TỆ NẠN XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 26, ma: "1.010938", ten: "Công bố tổ chức, cá nhân đủ điều kiện cung cấp dịch vụ cai nghiện ma túy tự nguyện tại gia đình, cộng đồng", linhVuc: "PHÒNG, CHỐNG TỆ NẠN XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 27, ma: "2.001661", ten: "Hỗ trợ học văn hóa, học nghề, trợ cấp khó khăn ban đầu cho nạn nhân", linhVuc: "PHÒNG, CHỐNG TỆ NẠN XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 28, ma: "1.004946", ten: "Áp dụng biện pháp can thiệp khẩn cấp hoặc tạm thời cách ly trẻ em khỏi môi trường/người gây tổn hại", linhVuc: "TRẺ EM", cap: "Xã", nhanh: false },
    { stt: 29, ma: "1.004944", ten: "Chấm dứt việc chăm sóc thay thế cho trẻ em", linhVuc: "TRẺ EM", cap: "Xã", nhanh: false },
    { stt: 30, ma: "2.001947", ten: "Phê duyệt kế hoạch hỗ trợ, can thiệp đối với trẻ em bị xâm hại hoặc có nguy cơ", linhVuc: "TRẺ EM", cap: "Xã", nhanh: false },
    { stt: 31, ma: "1.004941", ten: "Đăng ký nhận chăm sóc thay thế cho trẻ em (không phải người thân thích)", linhVuc: "TRẺ EM", cap: "Xã", nhanh: false },
    { stt: 32, ma: "2.001944", ten: "Thông báo nhận chăm sóc thay thế cho trẻ em (là người thân thích)", linhVuc: "TRẺ EM", cap: "Xã", nhanh: false },
    { stt: 33, ma: "2.001942", ten: "Chuyển trẻ em đang được chăm sóc thay thế tại cơ sở trợ giúp xã hội đến cá nhân, gia đình", linhVuc: "TRẺ EM", cap: "Xã", nhanh: false },
    { stt: 34, ma: "1.012085", ten: "Hủy bỏ Quyết định cấm tiếp xúc theo đơn đề nghị", linhVuc: "GIA ĐÌNH", cap: "Xã", nhanh: false },
    { stt: 35, ma: "1.012084", ten: "Cấm tiếp xúc theo Quyết định của Chủ tịch UBND cấp xã", linhVuc: "GIA ĐÌNH", cap: "Xã", nhanh: false },
    { stt: 36, ma: "1.013794", ten: "Gia hạn GCN đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng", linhVuc: "PHÁT THANH, TRUYỀN HÌNH VÀ THÔNG TIN ĐIỆN TỬ", cap: "Xã", nhanh: false },
    { stt: 37, ma: "1.013793", ten: "Sửa đổi, bổ sung GCN đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng", linhVuc: "PHÁT THANH, TRUYỀN HÌNH VÀ THÔNG TIN ĐIỆN TỬ", cap: "Xã", nhanh: false },
    { stt: 38, ma: "1.013792", ten: "Cấp GCN đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng", linhVuc: "PHÁT THANH, TRUYỀN HÌNH VÀ THÔNG TIN ĐIỆN TỬ", cap: "Xã", nhanh: false },
    { stt: 39, ma: "1.013795", ten: "Cấp lại GCN đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng", linhVuc: "PHÁT THANH, TRUYỀN HÌNH VÀ THÔNG TIN ĐIỆN TỬ", cap: "Xã", nhanh: false },
    { stt: 40, ma: "2.000794", ten: "Công nhận câu lạc bộ thể thao cơ sở", linhVuc: "THỂ DỤC THỂ THAO", cap: "Xã", nhanh: false },
    { stt: 41, ma: "1.013791", ten: "Tiếp nhận hồ sơ đăng ký lễ hội quy mô cấp xã", linhVuc: "VĂN HOÁ", cap: "Xã", nhanh: false },
    { stt: 42, ma: "1.003622", ten: "Thông báo tổ chức lễ hội cấp xã", linhVuc: "VĂN HOÁ", cap: "Xã", nhanh: false },
    { stt: 43, ma: "1.013750", ten: "Thăm viếng mộ liệt sĩ", linhVuc: "NGƯỜI CÓ CÔNG", cap: "Xã", nhanh: false },
    { stt: 44, ma: "1.010833", ten: "Cấp giấy xác nhận thân nhân của người có công", linhVuc: "NGƯỜI CÓ CÔNG", cap: "Xã", nhanh: false },
    { stt: 45, ma: "1.013734", ten: "Đăng ký hợp đồng lao động trực tiếp giao kết", linhVuc: "QUẢN LÝ LAO ĐỘNG NGOÀI NƯỚC", cap: "Xã", nhanh: false },
    { stt: 46, ma: "1.013715", ten: "Cho phép quỹ hoạt động trở lại sau khi bị tạm đình chỉ hoạt động", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 47, ma: "1.013714", ten: "Cấp lại giấy phép thành lập và công nhận điều lệ quỹ", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 48, ma: "1.013711", ten: "Cấp giấy phép thành lập và công nhận điều lệ quỹ", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 49, ma: "1.013709", ten: "Cho phép hội hoạt động trở lại sau khi bị đình chỉ có thời hạn", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 50, ma: "1.013707", ten: "Chia, tách; sáp nhập; hợp nhất hội", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 51, ma: "1.013704", ten: "Báo cáo tổ chức đại hội thành lập, đại hội nhiệm kỳ, đại hội bất thường của hội", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 52, ma: "1.013703", ten: "Thành lập hội", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 53, ma: "1.013717", ten: "Quỹ tự giải thể", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 54, ma: "1.013716", ten: "Hợp nhất, sáp nhập, chia, tách quỹ", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 55, ma: "1.013706", ten: "Thông báo kết quả đại hội và phê duyệt đổi tên hội, phê duyệt điều lệ hội", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 56, ma: "1.013702", ten: "Công nhận ban vận động thành lập hội", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 57, ma: "1.013713", ten: "Công nhận điều lệ (sửa đổi, bổ sung) quỹ; đổi tên quỹ", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 58, ma: "1.013708", ten: "Hội tự giải thể", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 59, ma: "1.013724", ten: "Vay vốn hỗ trợ tạo việc làm từ Quỹ quốc gia về việc làm đối với người lao động", linhVuc: "VIỆC LÀM", cap: "Xã", nhanh: false },
    { stt: 60, ma: "1.013725", ten: "Vay vốn hỗ trợ tạo việc làm từ Quỹ quốc gia về việc làm đối với cơ sở sản xuất, kinh doanh", linhVuc: "VIỆC LÀM", cap: "Xã", nhanh: false },
    { stt: 61, ma: "1.012592", ten: "Đăng ký hoạt động tín ngưỡng (cấp xã)", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 62, ma: "1.012591", ten: "Đăng ký bổ sung hoạt động tín ngưỡng (cấp xã)", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 63, ma: "1.012590", ten: "Đăng ký sinh hoạt tôn giáo tập trung (cấp xã)", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 64, ma: "1.012585", ten: "Đăng ký thay đổi người đại diện của nhóm sinh hoạt tôn giáo tập trung (cấp xã)", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 65, ma: "1.012584", ten: "Đề nghị thay đổi địa điểm sinh hoạt tôn giáo tập trung trong địa bàn một xã", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 66, ma: "1.012582", ten: "Đề nghị thay đổi địa điểm sinh hoạt tôn giáo tập trung đến địa bàn xã khác", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 67, ma: "1.013797", ten: "Đề nghị tổ chức cuộc lễ ngoài cơ sở tôn giáo (quy mô một xã)", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 68, ma: "1.013798", ten: "Đề nghị giảng đạo ngoài địa bàn phụ trách (quy mô trong một xã)", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 69, ma: "1.013796", ten: "Đề nghị tổ chức đại hội của tổ chức tôn giáo (địa bàn một xã)", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 70, ma: "1.012222", ten: "Công nhận người có uy tín", linhVuc: "CÔNG TÁC DÂN TỘC", cap: "Xã", nhanh: false },
    { stt: 71, ma: "1.012223", ten: "Đưa ra khỏi danh sách và thay thế, bổ sung người có uy tín trong đồng bào DTTS", linhVuc: "CÔNG TÁC DÂN TỘC", cap: "Xã", nhanh: false },
    { stt: 72, ma: "1.012971", ten: "Thành lập hoặc cho phép thành lập cơ sở giáo dục mầm non độc lập", linhVuc: "CÁC CƠ SỞ GIÁO DỤC KHÁC", cap: "Xã", nhanh: false },
    { stt: 73, ma: "1.012973", ten: "Sáp nhập, chia, tách cơ sở giáo dục mầm non độc lập", linhVuc: "CÁC CƠ SỞ GIÁO DỤC KHÁC", cap: "Xã", nhanh: false },
    { stt: 74, ma: "1.012972", ten: "Cho phép cơ sở giáo dục mầm non độc lập hoạt động trở lại", linhVuc: "CÁC CƠ SỞ GIÁO DỤC KHÁC", cap: "Xã", nhanh: false },
    { stt: 75, ma: "1.012974", ten: "Giải thể cơ sở giáo dục mầm non độc lập", linhVuc: "CÁC CƠ SỞ GIÁO DỤC KHÁC", cap: "Xã", nhanh: false },
    { stt: 76, ma: "1.012961", ten: "Thành lập hoặc cho phép thành lập trường mẫu giáo, trường mầm non, nhà trẻ", linhVuc: "GIÁO DỤC MẦM NON", cap: "Xã", nhanh: false },
    { stt: 77, ma: "1.012962", ten: "Giải thể trường mẫu giáo, trường mầm non, nhà trẻ", linhVuc: "GIÁO DỤC MẦM NON", cap: "Xã", nhanh: false },
    { stt: 78, ma: "1.006445", ten: "Sáp nhập, chia, tách trường mẫu giáo, trường mầm non, nhà trẻ", linhVuc: "GIÁO DỤC MẦM NON", cap: "Xã", nhanh: false },
    { stt: 79, ma: "1.006444", ten: "Cho phép trường mẫu giáo, trường mầm non, nhà trẻ hoạt động giáo dục trở lại", linhVuc: "GIÁO DỤC MẦM NON", cap: "Xã", nhanh: false },
    { stt: 80, ma: "1.006390", ten: "Cho phép trường mẫu giáo, trường mầm non, nhà trẻ hoạt động giáo dục", linhVuc: "GIÁO DỤC MẦM NON", cap: "Xã", nhanh: false },
    { stt: 81, ma: "1.012969", ten: "Thành lập hoặc cho phép thành lập trung tâm học tập cộng đồng", linhVuc: "GIÁO DỤC THƯỜNG XUYÊN", cap: "Xã", nhanh: false },
    { stt: 82, ma: "1.012970", ten: "Cho phép trung tâm học tập cộng đồng hoạt động trở lại", linhVuc: "GIÁO DỤC THƯỜNG XUYÊN", cap: "Xã", nhanh: false },
    { stt: 83, ma: "3.000308", ten: "Giải thể trung tâm học tập cộng đồng", linhVuc: "GIÁO DỤC THƯỜNG XUYÊN", cap: "Xã", nhanh: false },
    { stt: 84, ma: "3.000307", ten: "Sáp nhập, chia, tách trung tâm học tập cộng đồng", linhVuc: "GIÁO DỤC THƯỜNG XUYÊN", cap: "Xã", nhanh: false },
    { stt: 85, ma: "1.012963", ten: "Thành lập hoặc cho phép thành lập trường tiểu học", linhVuc: "GIÁO DỤC TIỂU HỌC", cap: "Xã", nhanh: false },
    { stt: 86, ma: "1.005099", ten: "Chuyển trường đối với học sinh tiểu học", linhVuc: "GIÁO DỤC TIỂU HỌC", cap: "Xã", nhanh: false },
    { stt: 87, ma: "1.004563", ten: "Sáp nhập, chia, tách trường tiểu học", linhVuc: "GIÁO DỤC TIỂU HỌC", cap: "Xã", nhanh: false },
    { stt: 88, ma: "2.001842", ten: "Cho phép trường tiểu học hoạt động giáo dục", linhVuc: "GIÁO DỤC TIỂU HỌC", cap: "Xã", nhanh: false },
    { stt: 89, ma: "1.004552", ten: "Cho phép trường tiểu học hoạt động giáo dục trở lại", linhVuc: "GIÁO DỤC TIỂU HỌC", cap: "Xã", nhanh: false },
    { stt: 90, ma: "1.001639", ten: "Giải thể trường tiểu học", linhVuc: "GIÁO DỤC TIỂU HỌC", cap: "Xã", nhanh: false },
    { stt: 91, ma: "1.012964", ten: "Thành lập hoặc cho phép thành lập trường THCS", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 92, ma: "1.012968", ten: "Giải thể trường THCS", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 93, ma: "1.012967", ten: "Sáp nhập, chia, tách trường THCS", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 94, ma: "1.012966", ten: "Cho phép trường THCS hoạt động giáo dục trở lại", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 95, ma: "1.012965", ten: "Cho phép trường THCS hoạt động giáo dục", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 96, ma: "2.002481", ten: "Chuyển trường đối với học sinh trung học cơ sở", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 97, ma: "3.000182", ten: "Tuyển sinh trung học cơ sở", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 98, ma: "3.000468", ten: "Chỉnh sửa nội dung văn bằng, chứng chỉ (tại cấp xã)", linhVuc: "VĂN BẰNG, CHỨNG CHỈ", cap: "Xã", nhanh: false },
    { stt: 99, ma: "3.000467", ten: "Cấp bản sao văn bằng, chứng chỉ từ sổ gốc (tại cấp xã)", linhVuc: "VĂN BẰNG, CHỨNG CHỈ", cap: "Xã", nhanh: false },
    { stt: 100, ma: "2.000101", ten: "Hòa giải tranh chấp đất đai", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 101, ma: "2.000102", ten: "Đăng ký đất đai, tài sản gắn liền với đất lần đầu", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 102, ma: "2.000103", ten: "Đăng ký biến động đất đai", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 103, ma: "5.000501", ten: "Cấp giấy phép xây dựng nhà ở riêng lẻ", linhVuc: "HOẠT ĐỘNG XÂY DỰNG", cap: "Xã", nhanh: false },
    { stt: 104, ma: "3.000301", ten: "Đăng ký nuôi con nuôi trong nước", linhVuc: "NUÔI CON NUÔI", cap: "Xã", nhanh: false },
    { stt: 105, ma: "4.000401", ten: "Hòa giải cơ sở", linhVuc: "HÒA GIẢI CƠ SỞ", cap: "Xã", nhanh: false },
    { stt: 106, ma: "9.000901", ten: "Đăng ký hộ kinh doanh", linhVuc: "HỘ KINH DOANH", cap: "Xã", nhanh: false },
    { stt: 107, ma: "9.000902", ten: "Thay đổi nội dung đăng ký hộ kinh doanh", linhVuc: "HỘ KINH DOANH", cap: "Xã", nhanh: false },
    { stt: 108, ma: "1.000894", ten: "Đăng ký kết hôn", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: true },
    { stt: 109, ma: "1.001022", ten: "Đăng ký nhận cha, mẹ, con", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 110, ma: "1.000689", ten: "Đăng ký khai sinh kết hợp nhận cha, mẹ, con", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 111, ma: "1.000593", ten: "Đăng ký kết hôn lưu động", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 112, ma: "1.000656", ten: "Đăng ký khai tử", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: true },
    { stt: 113, ma: "1.003583", ten: "Đăng ký khai sinh lưu động", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 114, ma: "1.000419", ten: "Đăng ký khai tử lưu động", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 115, ma: "1.004837", ten: "Đăng ký giám hộ", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 116, ma: "1.004845", ten: "Đăng ký chấm dứt giám hộ", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 117, ma: "3.000323", ten: "Đăng ký giám sát việc giám hộ", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 118, ma: "3.000322", ten: "Đăng ký chấm dứt giám sát việc giám hộ", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 119, ma: "1.004859", ten: "Thay đổi, cải chính, bổ sung thông tin hộ tịch, xác định lại dân tộc", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 120, ma: "1.004873", ten: "Cấp giấy xác nhận tình trạng hôn nhân", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: true },
    { stt: 121, ma: "1.004884", ten: "Đăng ký lại khai sinh", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 122, ma: "1.004772", ten: "Đăng ký khai sinh cho người đã có hồ sơ, giấy tờ cá nhân", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 123, ma: "1.004746", ten: "Đăng ký lại kết hôn", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 124, ma: "1.005461", ten: "Đăng ký lại khai tử", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 125, ma: "2.000528", ten: "Đăng ký khai sinh có yếu tố nước ngoài", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 126, ma: "2.000806", ten: "Đăng ký kết hôn có yếu tố nước ngoài", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 127, ma: "1.001766", ten: "Đăng ký khai tử có yếu tố nước ngoài", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 128, ma: "2.000779", ten: "Đăng ký nhận cha, mẹ, con có yếu tố nước ngoài", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 129, ma: "1.002211", ten: "Công nhận hòa giải viên (cấp xã)", linhVuc: "HÒA GIẢI CƠ SỞ", cap: "Xã", nhanh: false },
    { stt: 130, ma: "2.000930", ten: "Thôi làm hòa giải viên (cấp xã)", linhVuc: "HÒA GIẢI CƠ SỞ", cap: "Xã", nhanh: false },
    { stt: 131, ma: "2.002080", ten: "Thanh toán thù lao cho hòa giải viên", linhVuc: "HÒA GIẢI CƠ SỞ", cap: "Xã", nhanh: false },
    { stt: 132, ma: "1.013274", ten: "Cấp phép sử dụng tạm thời lòng đường, vỉa hè vào mục đích khác", linhVuc: "ĐƯỜNG BỘ", cap: "Xã", nhanh: false },
    { stt: 133, ma: "1.013061", ten: "Cấp giấy phép thi công công trình trên đường bộ đang khai thác", linhVuc: "ĐƯỜNG BỘ", cap: "Xã", nhanh: false },
    { stt: 134, ma: "1.000314", ten: "Chấp thuận vị trí đấu nối tạm vào đường bộ đang khai thác", linhVuc: "ĐƯỜNG BỘ", cap: "Xã", nhanh: false },
    { stt: 135, ma: "1.013225", ten: "Cấp giấy phép xây dựng mới đối với công trình cấp III, cấp IV và nhà ở riêng lẻ", linhVuc: "HOẠT ĐỘNG XÂY DỰNG", cap: "Xã", nhanh: false },
    { stt: 136, ma: "1.013229", ten: "Cấp giấy phép xây dựng sửa chữa, cải tạo đối với công trình cấp III, cấp IV và nhà ở riêng lẻ", linhVuc: "HOẠT ĐỘNG XÂY DỰNG", cap: "Xã", nhanh: false },
    { stt: 137, ma: "1.013232", ten: "Cấp giấy phép di dời đối với công trình cấp III, cấp IV và nhà ở riêng lẻ", linhVuc: "HOẠT ĐỘNG XÂY DỰNG", cap: "Xã", nhanh: false },
    { stt: 138, ma: "2.000620", ten: "Cấp Giấy phép bán lẻ rượu", linhVuc: "LƯU THÔNG HÀNG HÓA TRONG NƯỚC", cap: "Xã", nhanh: false },
    { stt: 139, ma: "2.001240", ten: "Cấp lại Giấy phép bán lẻ rượu", linhVuc: "LƯU THÔNG HÀNG HÓA TRONG NƯỚC", cap: "Xã", nhanh: false },
    { stt: 140, ma: "2.000615", ten: "Cấp sửa đổi, bổ sung Giấy phép bán lẻ rượu", linhVuc: "LƯU THÔNG HÀNG HÓA TRONG NƯỚC", cap: "Xã", nhanh: false },
    { stt: 141, ma: "2.000181", ten: "Cấp Giấy phép bán lẻ sản phẩm thuốc lá", linhVuc: "LƯU THÔNG HÀNG HÓA TRONG NƯỚC", cap: "Xã", nhanh: false },
    { stt: 142, ma: "2.000162", ten: "Cấp sửa đổi, bổ sung Giấy phép bán lẻ sản phẩm thuốc lá", linhVuc: "LƯU THÔNG HÀNG HÓA TRONG NƯỚC", cap: "Xã", nhanh: false },
    { stt: 143, ma: "2.000150", ten: "Cấp lại Giấy phép bán lẻ sản phẩm thuốc lá", linhVuc: "LƯU THÔNG HÀNG HÓA TRONG NƯỚC", cap: "Xã", nhanh: false },
    { stt: 144, ma: "2.000633", ten: "Cấp Giấy phép sản xuất rượu thủ công nhằm mục đích kinh doanh", linhVuc: "LƯU THÔNG HÀNG HÓA TRONG NƯỚC", cap: "Xã", nhanh: false },
    { stt: 145, ma: "1.001279", ten: "Cấp lại Giấy phép sản xuất rượu thủ công nhằm mục đích kinh doanh", linhVuc: "LƯU THÔNG HÀNG HÓA TRONG NƯỚC", cap: "Xã", nhanh: false },
    { stt: 146, ma: "1.013978", ten: "Đăng ký đất đai, tài sản gắn liền với đất, cấp GCN lần đầu đối với hộ gia đình, cá nhân", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 147, ma: "1.013967", ten: "Giải quyết tranh chấp đất đai thuộc thẩm quyền Chủ tịch UBND cấp xã", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 148, ma: "2.001215", ten: "Đăng ký phương tiện hoạt động vui chơi, giải trí dưới nước lần đầu", linhVuc: "HÀNG HẢI VÀ ĐƯỜNG THỦY", cap: "Xã", nhanh: false },
    { stt: 149, ma: "2.001214", ten: "Đăng ký lại phương tiện hoạt động vui chơi, giải trí dưới nước", linhVuc: "HÀNG HẢI VÀ ĐƯỜNG THỦY", cap: "Xã", nhanh: false },
    { stt: 150, ma: "2.001211", ten: "Xóa đăng ký phương tiện hoạt động vui chơi, giải trí dưới nước", linhVuc: "HÀNG HẢI VÀ ĐƯỜNG THỦY", cap: "Xã", nhanh: false },
    { stt: 151, ma: "1.005040", ten: "Xác nhận trình báo đường thủy nội địa hoặc trình báo bổ sung", linhVuc: "HÀNG HẢI VÀ ĐƯỜNG THỦY", cap: "Xã", nhanh: false },
    { stt: 152, ma: "1.002372", ten: "Xác nhận việc trình kháng nghị hàng hải", linhVuc: "HÀNG HẢI VÀ ĐƯỜNG THỦY", cap: "Xã", nhanh: false },
    { stt: 153, ma: "1.008004", ten: "Chuyển đổi cơ cấu cây trồng, vật nuôi trên đất trồng lúa", linhVuc: "TRỒNG TRỌT", cap: "Xã", nhanh: false },
    { stt: 154, ma: "3.000443", ten: "Công nhận khu vực biển cho cá nhân Việt Nam để nuôi trồng thủy sản", linhVuc: "BIỂN VÀ HẢI ĐẢO", cap: "Xã", nhanh: false },
    { stt: 155, ma: "1.012922", ten: "Lập biên bản kiểm tra hiện trường xác định nguyên nhân, mức độ thiệt hại rừng trồng", linhVuc: "LÂM NGHIỆP", cap: "Xã", nhanh: false },
    { stt: 156, ma: "1.012531", ten: "Hỗ trợ tín dụng đầu tư trồng rừng gỗ lớn đối với chủ rừng là hộ gia đình, cá nhân", linhVuc: "LÂM NGHIỆP", cap: "Xã", nhanh: false },
    { stt: 157, ma: "1.011471", ten: "Phê duyệt phương án khai thác gỗ, thực vật rừng ngoài gỗ loài thông thường (cấp xã)", linhVuc: "LÂM NGHIỆP", cap: "Xã", nhanh: false },
    { stt: 158, ma: "1.012694", ten: "Quyết định chuyển mục đích sử dụng rừng sang mục đích khác đối với cá nhân", linhVuc: "LÂM NGHIỆP", cap: "Xã", nhanh: false },
    { stt: 159, ma: "3.000250", ten: "Phê duyệt hoặc điều chỉnh phương án quản lý rừng bền vững (hộ gia đình, cá nhân, cộng đồng)", linhVuc: "LÂM NGHIỆP", cap: "Xã", nhanh: false },
    { stt: 160, ma: "1.007919", ten: "Thẩm định thiết kế, dự toán công trình lâm sinh sử dụng vốn đầu tư công", linhVuc: "LÂM NGHIỆP", cap: "Xã", nhanh: false },
    { stt: 161, ma: "3.000502", ten: "Thẩm định, phê duyệt phương án nuôi, trồng, thu hoạch cây dược liệu trong rừng", linhVuc: "LÂM NGHIỆP", cap: "Xã", nhanh: false },
    { stt: 162, ma: "1.012695", ten: "Quyết định thu hồi rừng đối với hộ gia đình, cá nhân, cộng đồng dân cư tự nguyện trả lại rừng", linhVuc: "LÂM NGHIỆP", cap: "Xã", nhanh: false },
    { stt: 163, ma: "2.002637", ten: "Đăng ký thành lập tổ hợp tác", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC", cap: "Xã", nhanh: false },
    { stt: 164, ma: "2.002638", ten: "Cấp lại giấy chứng nhận đăng ký tổ hợp tác do bị mất, cháy, rách, nát", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC", cap: "Xã", nhanh: false },
    { stt: 165, ma: "2.002639", ten: "Đăng ký thay đổi nội dung đăng ký tổ hợp tác", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC", cap: "Xã", nhanh: false },
    { stt: 166, ma: "2.002640", ten: "Hiệu đính, cập nhật, bổ sung thông tin đăng ký tổ hợp tác", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC", cap: "Xã", nhanh: false },
    { stt: 167, ma: "2.002641", ten: "Thông báo tạm ngừng kinh doanh, tiếp tục kinh doanh trở lại đối với tổ hợp tác", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC", cap: "Xã", nhanh: false },
    { stt: 168, ma: "2.002642", ten: "Chấm dứt hoạt động tổ hợp tác", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC", cap: "Xã", nhanh: false },
    { stt: 169, ma: "2.002226", ten: "Thông báo thành lập/thay đổi tổ hợp tác", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC", cap: "Xã", nhanh: false },
    { stt: 170, ma: "2.002228", ten: "Thông báo chấm dứt hoạt động của tổ hợp tác", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC", cap: "Xã", nhanh: false },
    { stt: 171, ma: "1.005280", ten: "Đăng ký thành lập hợp tác xã, liên hiệp HTX; chuyển đổi tổ hợp tác thành HTX; chia, tách, hợp nhất", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC, HỢP TÁC XÃ", cap: "Xã", nhanh: false },
    { stt: 172, ma: "1.005277", ten: "Đăng ký thay đổi nội dung đăng ký hợp tác xã, liên hiệp hợp tác xã", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC, HỢP TÁC XÃ", cap: "Xã", nhanh: false },
    { stt: 173, ma: "1.004901", ten: "Cấp đổi Giấy chứng nhận đăng ký hợp tác xã, liên hiệp hợp tác xã", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC, HỢP TÁC XÃ", cap: "Xã", nhanh: false },
    { stt: 174, ma: "1.004979", ten: "Thông báo thay đổi nội dung đăng ký hợp tác xã, liên hiệp hợp tác xã", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC, HỢP TÁC XÃ", cap: "Xã", nhanh: false },
    { stt: 175, ma: "2.002123", ten: "Đăng ký hoạt động chi nhánh, văn phòng đại diện, thông báo địa điểm kinh doanh HTX", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC, HỢP TÁC XÃ", cap: "Xã", nhanh: false },
    { stt: 176, ma: "1.005377", ten: "Thông báo tạm ngừng/tiếp tục kinh doanh HTX, chi nhánh, VPĐD, địa điểm kinh doanh", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC, HỢP TÁC XÃ", cap: "Xã", nhanh: false },
    { stt: 177, ma: "2.001973", ten: "Cấp lại Giấy chứng nhận đăng ký HTX, chi nhánh, VPĐD, địa điểm kinh doanh", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC, HỢP TÁC XÃ", cap: "Xã", nhanh: false },
    { stt: 178, ma: "1.004982", ten: "Đăng ký giải thể hợp tác xã, liên hiệp hợp tác xã", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC, HỢP TÁC XÃ", cap: "Xã", nhanh: false },
    { stt: 179, ma: "1.005010", ten: "Chấm dứt hoạt động chi nhánh, VPĐD, địa điểm kinh doanh của HTX", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC, HỢP TÁC XÃ", cap: "Xã", nhanh: false },
    { stt: 180, ma: "2.002668", ten: "Đăng ký nhu cầu hỗ trợ của tổ hợp tác, hợp tác xã, liên hiệp hợp tác xã", linhVuc: "HỖ TRỢ TỔ HỢP TÁC, HỢP TÁC XÃ", cap: "Xã", nhanh: false },
    { stt: 181, ma: "2.000720", ten: "Đăng ký thay đổi nội dung đăng ký hộ kinh doanh", linhVuc: "HỘ KINH DOANH", cap: "Xã", nhanh: false },
    { stt: 182, ma: "1.001570", ten: "Đăng ký tạm ngừng kinh doanh, tiếp tục kinh doanh trước thời hạn của hộ kinh doanh", linhVuc: "HỘ KINH DOANH", cap: "Xã", nhanh: false },
    { stt: 183, ma: "1.001266", ten: "Chấm dứt hoạt động hộ kinh doanh", linhVuc: "HỘ KINH DOANH", cap: "Xã", nhanh: false },
    { stt: 184, ma: "2.000575", ten: "Cấp lại / cấp đổi Giấy chứng nhận đăng ký hộ kinh doanh", linhVuc: "HỘ KINH DOANH", cap: "Xã", nhanh: false },
    { stt: 185, ma: "1.014034", ten: "Cập nhật, bổ sung, hiệu đính thông tin đăng ký hộ kinh doanh", linhVuc: "HỘ KINH DOANH", cap: "Xã", nhanh: false },
    { stt: 186, ma: "1.014035", ten: "Dừng thực hiện thủ tục đăng ký hộ kinh doanh", linhVuc: "HỘ KINH DOANH", cap: "Xã", nhanh: false },
    { stt: 187, ma: "1.011609", ten: "Công nhận hộ làm nông nghiệp, lâm nghiệp, ngư nghiệp và diêm nghiệp có mức sống trung bình", linhVuc: "GIẢM NGHÈO", cap: "Xã", nhanh: false },
    { stt: 188, ma: "3.000412", ten: "Công nhận người lao động có thu nhập thấp", linhVuc: "GIẢM NGHÈO", cap: "Xã", nhanh: false },
    { stt: 189, ma: "1.013226", ten: "Cấp điều chỉnh giấy phép xây dựng đối với công trình cấp III, cấp IV và nhà ở riêng lẻ", linhVuc: "HOẠT ĐỘNG XÂY DỰNG", cap: "Xã", nhanh: false },
    { stt: 190, ma: "1.013227", ten: "Gia hạn giấy phép xây dựng đối với công trình cấp III, cấp IV và nhà ở riêng lẻ", linhVuc: "HOẠT ĐỘNG XÂY DỰNG", cap: "Xã", nhanh: false },
    { stt: 191, ma: "1.013228", ten: "Cấp lại giấy phép xây dựng đối với công trình cấp III, cấp IV và nhà ở riêng lẻ", linhVuc: "HOẠT ĐỘNG XÂY DỰNG", cap: "Xã", nhanh: false },
    { stt: 192, ma: "1.013949", ten: "Giao đất, cho thuê đất, chuyển mục đích sử dụng đất; giao đất và giao rừng; gia hạn sử dụng đất", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 193, ma: "1.013965", ten: "Sử dụng đất kết hợp đa mục đích, gia hạn phương án sử dụng đất kết hợp đa mục đích", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 194, ma: "1.012812", ten: "Hòa giải tranh chấp đất đai", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 195, ma: "1.012796", ten: "Đính chính Giấy chứng nhận đã cấp lần đầu có sai sót", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 196, ma: "1.012817", ten: "Xác định lại diện tích đất ở của hộ gia đình, cá nhân đã được cấp GCN trước 01/7/2004", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 197, ma: "2.001621", ten: "Hỗ trợ đầu tư xây dựng phát triển thủy lợi nhỏ, thủy lợi nội đồng và tưới tiên tiến, tiết kiệm nước", linhVuc: "THỦY LỢI", cap: "Xã", nhanh: false },
    { stt: 198, ma: "1.003446", ten: "Thẩm định, phê duyệt phương án ứng phó thiên tai cho công trình, vùng hạ du đập (cấp xã)", linhVuc: "QUẢN LÝ ĐÊ ĐIỀU VÀ PCTT", cap: "Xã", nhanh: false },
    { stt: 199, ma: "1.003440", ten: "Thẩm định, phê duyệt phương án ứng phó với tình huống khẩn cấp (cấp xã)", linhVuc: "QUẢN LÝ ĐÊ ĐIỀU VÀ PCTT", cap: "Xã", nhanh: false },
    { stt: 200, ma: "1.010091", ten: "Hỗ trợ khám chữa bệnh, trợ cấp tai nạn cho lực lượng xung kích PCTT cấp xã", linhVuc: "QUẢN LÝ ĐÊ ĐIỀU VÀ PCTT", cap: "Xã", nhanh: false },
    { stt: 201, ma: "1.014027", ten: "Thực hiện, điều chỉnh, thôi hưởng trợ cấp hưu trí xã hội", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 202, ma: "1.014028", ten: "Hỗ trợ chi phí mai táng đối với đối tượng hưởng trợ cấp hưu trí xã hội", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 203, ma: "1.010820", ten: "Giải quyết chế độ người có công giúp đỡ cách mạng", linhVuc: "NGƯỜI CÓ CÔNG", cap: "Xã", nhanh: false },
    { stt: 204, ma: "1.010825", ten: "Bổ sung tình hình thân nhân trong hồ sơ liệt sĩ", linhVuc: "NGƯỜI CÓ CÔNG", cap: "Xã", nhanh: false },
    { stt: 205, ma: "1.009454", ten: "Công bố hoạt động bến thủy nội địa", linhVuc: "HÀNG HẢI VÀ ĐƯỜNG THỦY", cap: "Xã", nhanh: false },
    { stt: 206, ma: "1.009455", ten: "Công bố hoạt động bến khách ngang sông, bến thủy nội địa phục vụ thi công", linhVuc: "HÀNG HẢI VÀ ĐƯỜNG THỦY", cap: "Xã", nhanh: false },
    { stt: 207, ma: "1.003658", ten: "Công bố lại hoạt động bến thủy nội địa", linhVuc: "HÀNG HẢI VÀ ĐƯỜNG THỦY", cap: "Xã", nhanh: false },
    { stt: 208, ma: "1.014258", ten: "Xác nhận đăng ký thu hồi khoáng sản (cấp xã)", linhVuc: "KHOÁNG SẢN", cap: "Xã", nhanh: false },
    { stt: 209, ma: "1.014259", ten: "Quyết toán tiền cấp quyền khai thác khoáng sản (cấp xã)", linhVuc: "KHOÁNG SẢN", cap: "Xã", nhanh: false },
    { stt: 210, ma: "1.003596", ten: "Phê duyệt Kế hoạch khuyến nông địa phương (cấp xã)", linhVuc: "NÔNG NGHIỆP", cap: "Xã", nhanh: false },
    { stt: 211, ma: "2.001035", ten: "Chứng thực hợp đồng, giao dịch liên quan đến tài sản là động sản, quyền sử dụng đất, nhà ở", linhVuc: "CHỨNG THỰC", cap: "Xã", nhanh: true },
    { stt: 212, ma: "2.001019", ten: "Chứng thực di chúc", linhVuc: "CHỨNG THỰC", cap: "Xã", nhanh: false },
    { stt: 213, ma: "2.001016", ten: "Chứng thực văn bản từ chối nhận di sản", linhVuc: "CHỨNG THỰC", cap: "Xã", nhanh: false },
    { stt: 214, ma: "2.001406", ten: "Chứng thực văn bản thỏa thuận phân chia di sản (động sản, QSDĐ, nhà ở)", linhVuc: "CHỨNG THỰC", cap: "Xã", nhanh: false },
    { stt: 215, ma: "2.001009", ten: "Chứng thực văn bản khai nhận di sản (động sản, QSDĐ, nhà ở)", linhVuc: "CHỨNG THỰC", cap: "Xã", nhanh: false },
    { stt: 216, ma: "2.001008", ten: "Chứng thực chữ ký người dịch (không phải cộng tác viên dịch thuật UBND xã)", linhVuc: "CHỨNG THỰC", cap: "Xã", nhanh: true },
    { stt: 217, ma: "2.000992", ten: "Chứng thực chữ ký người dịch là cộng tác viên dịch thuật của UBND cấp xã", linhVuc: "CHỨNG THỰC", cap: "Xã", nhanh: true },
    { stt: 218, ma: "2.000913", ten: "Chứng thực việc sửa đổi, bổ sung, hủy bỏ hợp đồng, giao dịch", linhVuc: "CHỨNG THỰC", cap: "Xã", nhanh: true },
    { stt: 219, ma: "2.000927", ten: "Sửa lỗi sai sót trong hợp đồng, giao dịch đã được chứng thực", linhVuc: "CHỨNG THỰC", cap: "Xã", nhanh: true },
    { stt: 220, ma: "2.000942", ten: "Cấp bản sao từ bản chính hợp đồng, giao dịch đã được chứng thực", linhVuc: "CHỨNG THỰC", cap: "Xã", nhanh: true },
    { stt: 221, ma: "2.000908", ten: "Cấp bản sao từ bản gốc giấy tờ, văn bản do CQ có thẩm quyền cấp hoặc chứng nhận", linhVuc: "CHỨNG THỰC", cap: "Xã", nhanh: true },
    { stt: 222, ma: "2.000815", ten: "Chứng thực bản sao từ bản chính giấy tờ, văn bản", linhVuc: "CHỨNG THỰC", cap: "Xã", nhanh: true },
    { stt: 223, ma: "2.000884", ten: "Chứng thực chữ ký trong các giấy tờ, văn bản (kể cả điểm chỉ)", linhVuc: "CHỨNG THỰC", cap: "Xã", nhanh: true },
    { stt: 224, ma: "2.000635", ten: "Cấp bản sao trích lục hộ tịch", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: true },
    { stt: 225, ma: "2.002516", ten: "Xác nhận thông tin hộ tịch", linhVuc: "HỘ TỊCH", cap: "Xã", nhanh: false },
    { stt: 226, ma: "2.001263", ten: "Đăng ký việc nuôi con nuôi trong nước", linhVuc: "NUÔI CON NUÔI", cap: "Xã", nhanh: false },
    { stt: 227, ma: "2.001255", ten: "Đăng ký lại việc nuôi con nuôi trong nước", linhVuc: "NUÔI CON NUÔI", cap: "Xã", nhanh: false },
    { stt: 228, ma: "1.003005", ten: "Giải quyết việc người nước ngoài cư trú ở khu vực biên giới nhận trẻ em Việt Nam làm con nuôi", linhVuc: "NUÔI CON NUÔI", cap: "Xã", nhanh: false },
    { stt: 229, ma: "2.002363", ten: "Ghi vào sổ đăng ký nuôi con nuôi việc nuôi con nuôi đã giải quyết tại nước ngoài", linhVuc: "NUÔI CON NUÔI", cap: "Xã", nhanh: false },
    { stt: 230, ma: "2.002349", ten: "Cấp giấy xác nhận công dân VN thường trú biên giới đủ điều kiện nhận trẻ em nước láng giềng làm con nuôi", linhVuc: "NUÔI CON NUÔI", cap: "Xã", nhanh: false },
    { stt: 231, ma: "2.000424", ten: "Hỗ trợ khi hòa giải viên gặp tai nạn hoặc rủi ro ảnh hưởng sức khỏe, tính mạng khi hòa giải", linhVuc: "HÒA GIẢI CƠ SỞ", cap: "Xã", nhanh: false },
    { stt: 232, ma: "2.000950", ten: "Công nhận tổ trưởng tổ hòa giải (cấp xã)", linhVuc: "HÒA GIẢI CƠ SỞ", cap: "Xã", nhanh: false },
    { stt: 233, ma: "2.002165", ten: "Giải quyết yêu cầu bồi thường tại cơ quan trực tiếp quản lý người thi hành công vụ gây thiệt hại (cấp xã)", linhVuc: "BỒI THƯỜNG NHÀ NƯỚC", cap: "Xã", nhanh: false },
    { stt: 234, ma: "1.013950", ten: "Chuyển hình thức giao đất, cho thuê đất", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 235, ma: "1.013952", ten: "Điều chỉnh quyết định giao đất, cho thuê đất, chuyển mục đích do thay đổi căn cứ / thời hạn", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 236, ma: "1.013953", ten: "Điều chỉnh quyết định giao đất, cho thuê đất do sai sót ranh giới, vị trí, diện tích, mục đích", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 237, ma: "1.013962", ten: "Giao đất ở có thu tiền sử dụng đất không qua đấu giá cho đối tượng ưu tiên theo luật", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 238, ma: "1.013979", ten: "Tặng cho quyền sử dụng đất cho Nhà nước hoặc cộng đồng dân cư hoặc mở rộng đường GT", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 239, ma: "1.012818", ten: "Thu hồi GCN đã cấp không đúng quy định do người sử dụng đất phát hiện và cấp lại", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 240, ma: "1.012753", ten: "Đăng ký đất đai, cấp GCN lần đầu đối với tổ chức đang sử dụng đất", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 241, ma: "1.012836", ten: "Hỗ trợ chi phí vật tư phối giống nhân tạo gia súc (trâu, bò, lợn nái)", linhVuc: "CHĂN NUÔI", cap: "Xã", nhanh: false },
    { stt: 242, ma: "1.012837", ten: "Phê duyệt hỗ trợ kinh phí đào tạo, tập huấn chuyển đổi từ chăn nuôi; mua bình chứa Nitơ", linhVuc: "CHĂN NUÔI", cap: "Xã", nhanh: false },
    { stt: 243, ma: "1.013997", ten: "Hỗ trợ cơ sở sản xuất bị thiệt hại do dịch bệnh động vật", linhVuc: "THÚ Y", cap: "Xã", nhanh: false },
    { stt: 244, ma: "1.001662", ten: "Đăng ký khai thác, sử dụng nước dưới đất", linhVuc: "TÀI NGUYÊN NƯỚC", cap: "Xã", nhanh: false },
    { stt: 245, ma: "1.010736", ten: "Tham vấn trong đánh giá tác động môi trường", linhVuc: "MÔI TRƯỜNG", cap: "Xã", nhanh: false },
    { stt: 246, ma: "1.008603", ten: "Kê khai, thẩm định tờ khai phí bảo vệ môi trường đối với nước thải", linhVuc: "MÔI TRƯỜNG", cap: "Xã", nhanh: false },
    { stt: 247, ma: "1.013040", ten: "Khai, nộp phí bảo vệ môi trường đối với khí thải", linhVuc: "MÔI TRƯỜNG", cap: "Xã", nhanh: false },
    { stt: 248, ma: "3.000439", ten: "Giao khu vực biển cho cá nhân Việt Nam để nuôi trồng thủy sản", linhVuc: "BIỂN VÀ HẢI ĐẢO", cap: "Xã", nhanh: false },
    { stt: 249, ma: "3.000440", ten: "Gia hạn thời hạn giao khu vực biển cho cá nhân Việt Nam để NTTS", linhVuc: "BIỂN VÀ HẢI ĐẢO", cap: "Xã", nhanh: false },
    { stt: 250, ma: "3.000441", ten: "Trả lại khu vực biển cho cá nhân Việt Nam để NTTS", linhVuc: "BIỂN VÀ HẢI ĐẢO", cap: "Xã", nhanh: false },
    { stt: 251, ma: "3.000442", ten: "Sửa đổi, bổ sung Quyết định giao khu vực biển cho cá nhân Việt Nam để NTTS", linhVuc: "BIỂN VÀ HẢI ĐẢO", cap: "Xã", nhanh: false },
    { stt: 252, ma: "1.003956", ten: "Công nhận và giao quyền quản lý cho tổ chức cộng đồng (thủy sản)", linhVuc: "THỦY SẢN", cap: "Xã", nhanh: false },
    { stt: 253, ma: "1.004498", ten: "Sửa đổi, bổ sung quyết định công nhận và giao quyền quản lý cho tổ chức cộng đồng", linhVuc: "THỦY SẢN", cap: "Xã", nhanh: false },
    { stt: 254, ma: "1.004478", ten: "Công bố mở cảng cá loại III", linhVuc: "THỦY SẢN", cap: "Xã", nhanh: false },
    { stt: 255, ma: "1.003434", ten: "Hỗ trợ dự án liên kết (cấp xã)", linhVuc: "KINH TẾ HỢP TÁC VÀ PHÁT TRIỂN NÔNG THÔN", cap: "Xã", nhanh: false },
    { stt: 256, ma: "3.000410", ten: "Quyết định xác lập quyền sở hữu toàn dân đối với tài sản không có người thừa kế", linhVuc: "QUẢN LÝ CÔNG SẢN", cap: "Xã", nhanh: false },
    { stt: 257, ma: "3.000327", ten: "Giao tài sản kết cấu hạ tầng thủy lợi", linhVuc: "QUẢN LÝ CÔNG SẢN", cap: "Xã", nhanh: false },
    { stt: 258, ma: "3.000326", ten: "Thanh lý tài sản kết cấu hạ tầng thủy lợi; xử lý khi mất, hủy hoại", linhVuc: "QUẢN LÝ CÔNG SẢN", cap: "Xã", nhanh: false },
    { stt: 259, ma: "1.012994", ten: "Khấu trừ kinh phí bồi thường, hỗ trợ, tái định cư", linhVuc: "TÀI CHÍNH ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 260, ma: "1.012995", ten: "Ghi nợ tiền sử dụng đất của hộ gia đình, cá nhân trong trường hợp bố trí tái định cư", linhVuc: "TÀI CHÍNH ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 261, ma: "1.012996", ten: "Thanh toán, xóa nợ tiền sử dụng đất đối với hộ gia đình, cá nhân được ghi nợ", linhVuc: "TÀI CHÍNH ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 262, ma: "1.005412", ten: "Phê duyệt đối tượng được hỗ trợ phí bảo hiểm nông nghiệp", linhVuc: "BẢO HIỂM", cap: "Xã", nhanh: false },
    { stt: 263, ma: "1.012568", ten: "Giao tài sản kết cấu hạ tầng chợ do cấp xã quản lý", linhVuc: "TÀI SẢN KẾT CẤU HẠ TẦNG CHỢ", cap: "Xã", nhanh: false },
    { stt: 264, ma: "1.012569", ten: "Thu hồi tài sản kết cấu hạ tầng chợ", linhVuc: "TÀI SẢN KẾT CẤU HẠ TẦNG CHỢ", cap: "Xã", nhanh: false },
    { stt: 265, ma: "2.001283", ten: "Cấp Giấy chứng nhận đủ điều kiện cửa hàng bán lẻ LPG chai", linhVuc: "KINH DOANH KHÍ", cap: "Xã", nhanh: false },
    { stt: 266, ma: "2.001270", ten: "Cấp lại Giấy chứng nhận đủ điều kiện cửa hàng bán lẻ LPG chai", linhVuc: "KINH DOANH KHÍ", cap: "Xã", nhanh: false },
    { stt: 267, ma: "2.001261", ten: "Cấp điều chỉnh Giấy chứng nhận đủ điều kiện cửa hàng bán lẻ LPG chai", linhVuc: "KINH DOANH KHÍ", cap: "Xã", nhanh: false },
    { stt: 268, ma: "2.000629", ten: "Cấp sửa đổi, bổ sung Giấy phép sản xuất rượu thủ công nhằm mục đích kinh doanh", linhVuc: "LƯU THÔNG HÀNG HÓA TRONG NƯỚC", cap: "Xã", nhanh: false },
    { stt: 269, ma: "2.002096", ten: "Cấp Giấy chứng nhận sản phẩm công nghiệp nông thôn tiêu biểu cấp xã", linhVuc: "CÔNG NGHIỆP ĐỊA PHƯƠNG", cap: "Xã", nhanh: false },
    { stt: 270, ma: "1.010092", ten: "Trợ cấp tiền tuất, tai nạn cho lực lượng xung kích PCTT cấp xã chưa tham gia BHXH", linhVuc: "QUẢN LÝ ĐÊ ĐIỀU VÀ PCTT", cap: "Xã", nhanh: false },
    { stt: 271, ma: "1.004082", ten: "Xác nhận Hợp đồng tiếp cận nguồn gen và chia sẻ lợi ích (cấp xã)", linhVuc: "BẢO TỒN THIÊN NHIÊN VÀ ĐA DẠNG SINH HỌC", cap: "Xã", nhanh: false },
    { stt: 272, ma: "1.009452", ten: "Thỏa thuận thông số kỹ thuật xây dựng bến thủy nội địa", linhVuc: "HÀNG HẢI VÀ ĐƯỜNG THỦY", cap: "Xã", nhanh: false },
    { stt: 273, ma: "1.009453", ten: "Thỏa thuận thông số kỹ thuật xây dựng bến khách ngang sông, bến thủy nội địa phục vụ thi công", linhVuc: "HÀNG HẢI VÀ ĐƯỜNG THỦY", cap: "Xã", nhanh: false },
    { stt: 274, ma: "2.001212", ten: "Cấp lại giấy chứng nhận đăng ký phương tiện hoạt động vui chơi, giải trí dưới nước", linhVuc: "HÀNG HẢI VÀ ĐƯỜNG THỦY", cap: "Xã", nhanh: false },
    { stt: 275, ma: "2.001217", ten: "Đóng, không cho phép hoạt động tại vùng nước khác (phao/cờ hiệu)", linhVuc: "HÀNG HẢI VÀ ĐƯỜNG THỦY", cap: "Xã", nhanh: false },
    { stt: 276, ma: "2.001218", ten: "Công bố mở, cho phép hoạt động tại vùng nước khác (phao/cờ hiệu)", linhVuc: "HÀNG HẢI VÀ ĐƯỜNG THỦY", cap: "Xã", nhanh: false },
    { stt: 277, ma: "1.014275", ten: "Tổ chức kinh tế nhận chuyển nhượng, thuê QSDĐ, nhận góp vốn bằng QSDĐ để thực hiện dự án đầu tư", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 278, ma: "1.014284", ten: "Giao đất, cho thuê đất, giao khu vực biển để thực hiện hoạt động lấn biển", linhVuc: "ĐẤT ĐAI", cap: "Xã", nhanh: false },
    { stt: 279, ma: "1.003347", ten: "Phê duyệt, công bố công khai quy trình vận hành hồ chứa thủy lợi thuộc thẩm quyền Chủ tịch UBND cấp xã", linhVuc: "THỦY LỢI", cap: "Xã", nhanh: false },
    { stt: 280, ma: "1.003471", ten: "Phê duyệt đề cương, kết quả kiểm định an toàn đập, hồ chứa thủy lợi (cấp xã)", linhVuc: "THỦY LỢI", cap: "Xã", nhanh: false },
    { stt: 281, ma: "1.013768", ten: "Phê duyệt phương án bảo vệ đập, hồ chứa nước trên địa bàn do UBND cấp tỉnh phân cấp", linhVuc: "THỦY LỢI", cap: "Xã", nhanh: false },
    { stt: 282, ma: "2.002501", ten: "Xử lý đơn tại cấp xã", linhVuc: "XỬ LÝ ĐƠN THƯ", cap: "Xã", nhanh: false },
    { stt: 283, ma: "1.000280", ten: "Công nhận trường tiểu học đạt chuẩn quốc gia", linhVuc: "GIÁO DỤC TIỂU HỌC", cap: "Xã", nhanh: false },
    { stt: 284, ma: "1.000288", ten: "Công nhận trường mầm non đạt chuẩn Quốc gia", linhVuc: "GIÁO DỤC MẦM NON", cap: "Xã", nhanh: false },
    { stt: 285, ma: "1.000691", ten: "Công nhận trường trung học đạt chuẩn Quốc gia", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 286, ma: "1.001622", ten: "Hỗ trợ ăn trưa đối với trẻ em mẫu giáo", linhVuc: "GIÁO DỤC VÀ ĐÀO TẠO", cap: "Xã", nhanh: false },
    { stt: 287, ma: "1.001714", ten: "Cấp học bổng và hỗ trợ kinh phí mua phương tiện, đồ dùng học tập cho người khuyết tật", linhVuc: "GIÁO DỤC VÀ ĐÀO TẠO", cap: "Xã", nhanh: false },
    { stt: 288, ma: "1.002407", ten: "Xét, cấp học bổng chính sách", linhVuc: "GIÁO DỤC VÀ ĐÀO TẠO", cap: "Xã", nhanh: false },
    { stt: 289, ma: "1.003702", ten: "Hỗ trợ học tập đối với trẻ mẫu giáo, học sinh tiểu học, THCS, sinh viên DTTS rất ít người", linhVuc: "GIÁO DỤC VÀ ĐÀO TẠO", cap: "Xã", nhanh: false },
    { stt: 290, ma: "1.008950", ten: "Trợ cấp đối với trẻ em mầm non là con công nhân, người lao động làm việc tại khu công nghiệp", linhVuc: "GIÁO DỤC VÀ ĐÀO TẠO", cap: "Xã", nhanh: false },
    { stt: 291, ma: "1.008951", ten: "Hỗ trợ đối với giáo viên mầm non làm việc tại cơ sở giáo dục mầm non dân lập, tư thục ở địa bàn KCN", linhVuc: "GIÁO DỤC VÀ ĐÀO TẠO", cap: "Xã", nhanh: false },
    { stt: 292, ma: "2.002481", ten: "Chuyển trường đối với học sinh trung học cơ sở", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 293, ma: "2.002482", ten: "Tiếp nhận học sinh trung học cơ sở Việt Nam về nước", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 294, ma: "2.002483", ten: "Tiếp nhận học sinh trung học cơ sở người nước ngoài", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 295, ma: "2.001904", ten: "Tiếp nhận đối tượng học bổ túc trung học cơ sở", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 296, ma: "1.005108", ten: "Thuyên chuyển đối tượng học bổ túc trung học cơ sở", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 297, ma: "2.002284", ten: "Cấp chính sách nội trú cho HSSV chương trình đào tạo CĐ, TC tại CSGDNN công lập trực thuộc xã", linhVuc: "GIÁO DỤC NGHỀ NGHIỆP", cap: "Xã", nhanh: false },
    { stt: 298, ma: "2.001960", ten: "Cấp chính sách nội trú cho HSSV tại CSGDNN tư thục hoặc có vốn đầu tư nước ngoài", linhVuc: "GIÁO DỤC NGHỀ NGHIỆP", cap: "Xã", nhanh: false },
    { stt: 299, ma: "1.001000", ten: "Xác nhận hoạt động giáo dục kỹ năng sống và hoạt động giáo dục ngoài giờ chính khóa", linhVuc: "CÁC CƠ SỞ GIÁO DỤC KHÁC", cap: "Xã", nhanh: false },
    { stt: 300, ma: "3.000309", ten: "Thành lập lớp dành cho người khuyết tật trong trường MN, TH, THCS và TT GDTX", linhVuc: "CÁC CƠ SỞ GIÁO DỤC KHÁC", cap: "Xã", nhanh: false },
    { stt: 301, ma: "1.012975", ten: "Cho phép cơ sở giáo dục khác thực hiện chương trình giáo dục phổ thông cấp tiểu học", linhVuc: "CÁC CƠ SỞ GIÁO DỤC KHÁC", cap: "Xã", nhanh: false },
    { stt: 302, ma: "1.008724", ten: "Chuyển đổi nhà trẻ, trường mẫu giáo, mầm non tư thục sang hoạt động không vì lợi nhuận", linhVuc: "GIÁO DỤC MẦM NON", cap: "Xã", nhanh: false },
    { stt: 303, ma: "1.008725", ten: "Chuyển đổi trường tiểu học, THCS tư thục sang hoạt động không vì lợi nhuận", linhVuc: "GIÁO DỤC VÀ ĐÀO TẠO", cap: "Xã", nhanh: false },
    { stt: 304, ma: "1.005143", ten: "Phê duyệt việc dạy và học bằng tiếng nước ngoài", linhVuc: "GIÁO DỤC VÀ ĐÀO TẠO", cap: "Xã", nhanh: false },
    { stt: 305, ma: "2.002594", ten: "Đề nghị đánh giá, công nhận Đơn vị học tập cấp huyện", linhVuc: "GIÁO DỤC VÀ ĐÀO TẠO", cap: "Xã", nhanh: false },
    { stt: 306, ma: "1.013710", ten: "Hỗ trợ chi phí y tế và thu nhập thực tế bị mất cho người trực tiếp tham gia hoạt động chữ thập đỏ bị tai nạn", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 307, ma: "1.005358", ten: "Thẩm định hồ sơ người đang trực tiếp tham gia hoạt động chữ thập đỏ bị tai nạn", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 308, ma: "1.005201", ten: "Xem xét, chi trả chi phí cho người tham gia hoạt động chữ thập đỏ bị tai nạn", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 309, ma: "1.013712", ten: "Công nhận quỹ đủ điều kiện hoạt động và công nhận thành viên HĐQL quỹ", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 310, ma: "1.011548", ten: "Vay vốn hỗ trợ tạo việc làm từ Quỹ quốc gia về việc làm đối với người lao động", linhVuc: "VIỆC LÀM", cap: "Xã", nhanh: false },
    { stt: 311, ma: "1.011550", ten: "Vay vốn hỗ trợ tạo việc làm từ Quỹ quốc gia về việc làm đối với cơ sở SXKD", linhVuc: "VIỆC LÀM", cap: "Xã", nhanh: false },
    { stt: 312, ma: "1.012598", ten: "Đề nghị tổ chức cuộc lễ ngoài cơ sở tôn giáo (quy mô một huyện - tiếp nhận cấp xã)", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 313, ma: "2.001842", ten: "Cho phép trường tiểu học hoạt động giáo dục", linhVuc: "GIÁO DỤC TIỂU HỌC", cap: "Xã", nhanh: false },
    { stt: 314, ma: "1.006390", ten: "Cho phép trường mẫu giáo, mầm non, nhà trẻ hoạt động giáo dục", linhVuc: "GIÁO DỤC MẦM NON", cap: "Xã", nhanh: false },
    { stt: 315, ma: "1.012965", ten: "Cho phép trường THCS hoạt động giáo dục", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 316, ma: "3.000182", ten: "Tuyển sinh trung học cơ sở", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 317, ma: "1.005099", ten: "Chuyển trường đối với học sinh tiểu học", linhVuc: "GIÁO DỤC TIỂU HỌC", cap: "Xã", nhanh: false },
    { stt: 318, ma: "1.004563", ten: "Sáp nhập, chia, tách trường tiểu học", linhVuc: "GIÁO DỤC TIỂU HỌC", cap: "Xã", nhanh: false },
    { stt: 319, ma: "1.004552", ten: "Cho phép trường tiểu học hoạt động giáo dục trở lại", linhVuc: "GIÁO DỤC TIỂU HỌC", cap: "Xã", nhanh: false },
    { stt: 320, ma: "1.001639", ten: "Giải thể trường tiểu học", linhVuc: "GIÁO DỤC TIỂU HỌC", cap: "Xã", nhanh: false },
    { stt: 321, ma: "1.012963", ten: "Thành lập hoặc cho phép thành lập trường tiểu học", linhVuc: "GIÁO DỤC TIỂU HỌC", cap: "Xã", nhanh: false },
    { stt: 322, ma: "1.012964", ten: "Thành lập hoặc cho phép thành lập trường THCS", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 323, ma: "1.012966", ten: "Cho phép trường THCS hoạt động giáo dục trở lại", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 324, ma: "1.012967", ten: "Sáp nhập, chia, tách trường THCS", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 325, ma: "1.012968", ten: "Giải thể trường THCS", linhVuc: "GIÁO DỤC TRUNG HỌC", cap: "Xã", nhanh: false },
    { stt: 326, ma: "1.012961", ten: "Thành lập hoặc cho phép thành lập trường mẫu giáo, mầm non, nhà trẻ", linhVuc: "GIÁO DỤC MẦM NON", cap: "Xã", nhanh: false },
    { stt: 327, ma: "1.012962", ten: "Giải thể trường mẫu giáo, mầm non, nhà trẻ", linhVuc: "GIÁO DỤC MẦM NON", cap: "Xã", nhanh: false },
    { stt: 328, ma: "1.006444", ten: "Cho phép trường mẫu giáo, mầm non, nhà trẻ hoạt động giáo dục trở lại", linhVuc: "GIÁO DỤC MẦM NON", cap: "Xã", nhanh: false },
    { stt: 329, ma: "1.006445", ten: "Sáp nhập, chia, tách trường mẫu giáo, mầm non, nhà trẻ", linhVuc: "GIÁO DỤC MẦM NON", cap: "Xã", nhanh: false },
    { stt: 330, ma: "1.012969", ten: "Thành lập hoặc cho phép thành lập trung tâm học tập cộng đồng", linhVuc: "GIÁO DỤC THƯỜNG XUYÊN", cap: "Xã", nhanh: false },
    { stt: 331, ma: "1.012970", ten: "Cho phép trung tâm học tập cộng đồng hoạt động trở lại", linhVuc: "GIÁO DỤC THƯỜNG XUYÊN", cap: "Xã", nhanh: false },
    { stt: 332, ma: "3.000307", ten: "Sáp nhập, chia, tách trung tâm học tập cộng đồng", linhVuc: "GIÁO DỤC THƯỜNG XUYÊN", cap: "Xã", nhanh: false },
    { stt: 333, ma: "3.000308", ten: "Giải thể trung tâm học tập cộng đồng", linhVuc: "GIÁO DỤC THƯỜNG XUYÊN", cap: "Xã", nhanh: false },
    { stt: 334, ma: "1.012971", ten: "Thành lập hoặc cho phép thành lập cơ sở giáo dục mầm non độc lập", linhVuc: "CÁC CƠ SỞ GIÁO DỤC KHÁC", cap: "Xã", nhanh: false },
    { stt: 335, ma: "1.012972", ten: "Cho phép cơ sở giáo dục mầm non độc lập hoạt động trở lại", linhVuc: "CÁC CƠ SỞ GIÁO DỤC KHÁC", cap: "Xã", nhanh: false },
    { stt: 336, ma: "1.012973", ten: "Sáp nhập, chia, tách cơ sở giáo dục mầm non độc lập", linhVuc: "CÁC CƠ SỞ GIÁO DỤC KHÁC", cap: "Xã", nhanh: false },
    { stt: 337, ma: "1.012974", ten: "Giải thể cơ sở giáo dục mầm non độc lập", linhVuc: "CÁC CƠ SỞ GIÁO DỤC KHÁC", cap: "Xã", nhanh: false },
    { stt: 338, ma: "2.002080", ten: "Thanh toán thù lao cho hòa giải viên", linhVuc: "HÒA GIẢI CƠ SỞ", cap: "Xã", nhanh: false },
    { stt: 339, ma: "1.013791", ten: "Tiếp nhận hồ sơ đăng ký lễ hội quy mô cấp xã", linhVuc: "VĂN HOÁ", cap: "Xã", nhanh: false },
    { stt: 340, ma: "1.003622", ten: "Thông báo tổ chức lễ hội cấp xã", linhVuc: "VĂN HOÁ", cap: "Xã", nhanh: false },
    { stt: 341, ma: "2.000794", ten: "Công nhận câu lạc bộ thể thao cơ sở", linhVuc: "THỂ DỤC THỂ THAO", cap: "Xã", nhanh: false },
    { stt: 342, ma: "1.013792", ten: "Cấp GCN đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng", linhVuc: "PHÁT THANH, TRUYỀN HÌNH VÀ THÔNG TIN ĐIỆN TỬ", cap: "Xã", nhanh: false },
    { stt: 343, ma: "1.013793", ten: "Sửa đổi, bổ sung GCN đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng", linhVuc: "PHÁT THANH, TRUYỀN HÌNH VÀ THÔNG TIN ĐIỆN TỬ", cap: "Xã", nhanh: false },
    { stt: 344, ma: "1.013794", ten: "Gia hạn GCN đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng", linhVuc: "PHÁT THANH, TRUYỀN HÌNH VÀ THÔNG TIN ĐIỆN TỬ", cap: "Xã", nhanh: false },
    { stt: 345, ma: "1.013795", ten: "Cấp lại GCN đủ điều kiện hoạt động điểm cung cấp dịch vụ trò chơi điện tử công cộng", linhVuc: "PHÁT THANH, TRUYỀN HÌNH VÀ THÔNG TIN ĐIỆN TỬ", cap: "Xã", nhanh: false },
    { stt: 346, ma: "1.013750", ten: "Thăm viếng mộ liệt sĩ", linhVuc: "NGƯỜI CÓ CÔNG", cap: "Xã", nhanh: false },
    { stt: 347, ma: "1.010833", ten: "Cấp giấy xác nhận thân nhân của người có công", linhVuc: "NGƯỜI CÓ CÔNG", cap: "Xã", nhanh: false },
    { stt: 348, ma: "1.013734", ten: "Đăng ký hợp đồng lao động trực tiếp giao kết", linhVuc: "QUẢN LÝ LAO ĐỘNG NGOÀI NƯỚC", cap: "Xã", nhanh: false },
    { stt: 349, ma: "1.012222", ten: "Công nhận người có uy tín", linhVuc: "CÔNG TÁC DÂN TỘC", cap: "Xã", nhanh: false },
    { stt: 350, ma: "1.012223", ten: "Đưa ra khỏi danh sách và thay thế, bổ sung người có uy tín trong đồng bào DTTS", linhVuc: "CÔNG TÁC DÂN TỘC", cap: "Xã", nhanh: false },
    { stt: 351, ma: "1.001776", ten: "Thực hiện, điều chỉnh, thôi hưởng trợ cấp xã hội hàng tháng, hỗ trợ kinh phí chăm sóc nuôi dưỡng hàng tháng", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 352, ma: "1.001731", ten: "Hỗ trợ chi phí mai táng cho đối tượng bảo trợ xã hội", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 353, ma: "1.001699", ten: "Xác định, xác định lại mức độ khuyết tật và cấp Giấy xác nhận khuyết tật", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 354, ma: "1.001653", ten: "Đổi, cấp lại Giấy xác nhận khuyết tật", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 355, ma: "2.000477", ten: "Dừng trợ giúp xã hội tại cơ sở trợ giúp xã hội", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 356, ma: "2.000355", ten: "Đăng ký hoạt động đối với cơ sở trợ giúp xã hội dưới 10 đối tượng có hoàn cảnh khó khăn", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 357, ma: "2.000286", ten: "Tiếp nhận đối tượng bảo trợ xã hội có hoàn cảnh đặc biệt khó khăn vào cơ sở trợ giúp xã hội", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 358, ma: "2.000282", ten: "Tiếp nhận đối tượng cần bảo vệ khẩn cấp vào cơ sở trợ giúp xã hội", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 359, ma: "1.013821", ten: "Thực hiện, điều chỉnh, tạm dừng, thôi hưởng trợ cấp sinh hoạt hàng tháng đối với nghệ nhân ND, NN ưu tú", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 360, ma: "1.013822", ten: "Hỗ trợ chi phí mai táng đối với nghệ nhân ND, NN ưu tú có thu nhập thấp", linhVuc: "BẢO TRỢ XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 361, ma: "2.001088", ten: "Xét hưởng chính sách hỗ trợ cho đối tượng sinh con đúng chính sách dân số", linhVuc: "DÂN SỐ, BÀ MẸ - TRẺ EM", cap: "Xã", nhanh: false },
    { stt: 362, ma: "1.010939", ten: "Công bố lại tổ chức, cá nhân cung cấp dịch vụ cai nghiện ma túy tự nguyện tại gia đình, cộng đồng", linhVuc: "PHÒNG, CHỐNG TỆ NẠN XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 363, ma: "1.010941", ten: "Đăng ký cai nghiện ma túy tự nguyện", linhVuc: "PHÒNG, CHỐNG TỆ NẠN XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 364, ma: "1.010940", ten: "Công bố cơ sở cai nghiện ma túy tự nguyện, cơ sở cai nghiện công lập đủ điều kiện", linhVuc: "PHÒNG, CHỐNG TỆ NẠN XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 365, ma: "1.010938", ten: "Công bố tổ chức, cá nhân đủ điều kiện cung cấp dịch vụ cai nghiện ma túy tự nguyện tại gia đình, cộng đồng", linhVuc: "PHÒNG, CHỐNG TỆ NẠN XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 366, ma: "2.001661", ten: "Hỗ trợ học văn hóa, học nghề, trợ cấp khó khăn ban đầu cho nạn nhân", linhVuc: "PHÒNG, CHỐNG TỆ NẠN XÃ HỘI", cap: "Xã", nhanh: false },
    { stt: 367, ma: "1.004946", ten: "Áp dụng biện pháp can thiệp khẩn cấp hoặc tạm thời cách ly trẻ em khỏi môi trường/người gây tổn hại", linhVuc: "TRẺ EM", cap: "Xã", nhanh: false },
    { stt: 368, ma: "1.004944", ten: "Chấm dứt việc chăm sóc thay thế cho trẻ em", linhVuc: "TRẺ EM", cap: "Xã", nhanh: false },
    { stt: 369, ma: "2.001947", ten: "Phê duyệt kế hoạch hỗ trợ, can thiệp đối với trẻ em bị xâm hại hoặc có nguy cơ", linhVuc: "TRẺ EM", cap: "Xã", nhanh: false },
    { stt: 370, ma: "1.004941", ten: "Đăng ký nhận chăm sóc thay thế cho trẻ em (không phải người thân thích)", linhVuc: "TRẺ EM", cap: "Xã", nhanh: false },
    { stt: 371, ma: "2.001944", ten: "Thông báo nhận chăm sóc thay thế cho trẻ em (là người thân thích)", linhVuc: "TRẺ EM", cap: "Xã", nhanh: false },
    { stt: 372, ma: "2.001942", ten: "Chuyển trẻ em đang được chăm sóc thay thế tại cơ sở trợ giúp xã hội đến cá nhân, gia đình", linhVuc: "TRẺ EM", cap: "Xã", nhanh: false },
    { stt: 373, ma: "1.012085", ten: "Hủy bỏ Quyết định cấm tiếp xúc theo đơn đề nghị", linhVuc: "GIA ĐÌNH", cap: "Xã", nhanh: false },
    { stt: 374, ma: "1.012084", ten: "Cấm tiếp xúc theo Quyết định của Chủ tịch UBND cấp xã", linhVuc: "GIA ĐÌNH", cap: "Xã", nhanh: false },
    { stt: 375, ma: "1.013703", ten: "Thành lập hội", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 376, ma: "1.013702", ten: "Công nhận ban vận động thành lập hội", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 377, ma: "1.013704", ten: "Báo cáo tổ chức đại hội thành lập, đại hội nhiệm kỳ, đại hội bất thường của hội", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 378, ma: "1.013706", ten: "Thông báo kết quả đại hội và phê duyệt đổi tên hội, phê duyệt điều lệ hội", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 379, ma: "1.013707", ten: "Chia, tách; sáp nhập; hợp nhất hội", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 380, ma: "1.013708", ten: "Hội tự giải thể", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 381, ma: "1.013709", ten: "Cho phép hội hoạt động trở lại sau khi bị đình chỉ có thời hạn", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 382, ma: "1.013711", ten: "Cấp giấy phép thành lập và công nhận điều lệ quỹ", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 383, ma: "1.013713", ten: "Công nhận điều lệ (sửa đổi, bổ sung) quỹ; đổi tên quỹ", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 384, ma: "1.013714", ten: "Cấp lại giấy phép thành lập và công nhận điều lệ quỹ", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 385, ma: "1.013715", ten: "Cho phép quỹ hoạt động trở lại sau khi bị tạm đình chỉ hoạt động", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 386, ma: "1.013716", ten: "Hợp nhất, sáp nhập, chia, tách quỹ", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 387, ma: "1.013717", ten: "Quỹ tự giải thể", linhVuc: "QUẢN LÝ NHÀ NƯỚC VỀ HỘI, QUỸ", cap: "Xã", nhanh: false },
    { stt: 388, ma: "1.012592", ten: "Đăng ký hoạt động tín ngưỡng (cấp xã)", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 389, ma: "1.012591", ten: "Đăng ký bổ sung hoạt động tín ngưỡng (cấp xã)", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 390, ma: "1.012590", ten: "Đăng ký sinh hoạt tôn giáo tập trung (cấp xã)", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 391, ma: "1.012585", ten: "Đăng ký thay đổi người đại diện của nhóm sinh hoạt tôn giáo tập trung (cấp xã)", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 392, ma: "1.012584", ten: "Đề nghị thay đổi địa điểm sinh hoạt tôn giáo tập trung trong địa bàn một xã", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 393, ma: "1.012582", ten: "Đề nghị thay đổi địa điểm sinh hoạt tôn giáo tập trung đến địa bàn xã khác", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 394, ma: "1.013796", ten: "Đề nghị tổ chức đại hội của tổ chức tôn giáo (địa bàn một xã)", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 395, ma: "1.013797", ten: "Đề nghị tổ chức cuộc lễ ngoài cơ sở tôn giáo (quy mô một xã)", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 396, ma: "1.013798", ten: "Đề nghị giảng đạo ngoài địa bàn phụ trách (quy mô trong một xã)", linhVuc: "TÍN NGƯỠNG, TÔN GIÁO", cap: "Xã", nhanh: false },
    { stt: 397, ma: "3.000467", ten: "Cấp bản sao văn bằng, chứng chỉ từ sổ gốc (tại cấp xã)", linhVuc: "VĂN BẰNG, CHỨNG CHỈ", cap: "Xã", nhanh: false },
    { stt: 398, ma: "3.000468", ten: "Chỉnh sửa nội dung văn bằng, chứng chỉ (tại cấp xã)", linhVuc: "VĂN BẰNG, CHỨNG CHỈ", cap: "Xã", nhanh: false },
    { stt: 399, ma: "2.002635", ten: "Đề nghị thay đổi tên tổ hợp tác, HTX do xâm phạm quyền sở hữu công nghiệp", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC, HỢP TÁC XÃ", cap: "Xã", nhanh: false },
    { stt: 400, ma: "2.002636", ten: "Đề nghị thu hồi GCN đăng ký tổ hợp tác, HTX do kê khai giả mạo", linhVuc: "THÀNH LẬP VÀ HOẠT ĐỘNG CỦA TỔ HỢP TÁC, HỢP TÁC XÃ", cap: "Xã", nhanh: false }
  ]
};
